services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql     
      - ./scripts/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./scripts/files:/files
volumes:
  pgdata:
    driver: local