services:
  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
    volumes:
      - pgdata:/var/lib/postgresql     
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  pgdata:
    driver: local